### ISSUE TITLE
Invalid dataset ID "githubarchive:day"

### ISSUE THREAD

**Issue by tyler17** [abronte/BigQuery#27]
To connect to the datasets from githubarchive.org, what do I set 
opts['dataset'] to?

I've tried opts['dataset'] = 'githubarchive:day' and opts['dataset'] = 'githubarchive:day.events_20150729'

but they both return saying invalid dataset. Do I have to add these datasets to my project somehow?

**Comment by venturehacker** [comment]
Nevermind, I just tried not defining opts['database'] and specifiing the desired table in the query and that worked.

**Comment by tyler17** [comment]
Nevermind, I got it to work by not specifying the opts['dataset'] field at all.
