### ISSUE TITLE
Insert Ruby Timestamp Example

### ISSUE THREAD

**Issue by jkeung** [abronte/BigQuery#41]
I am trying to use the insert data example, except I am trying to load into a timestamp field. This doesn't seem to be working for me. I have tried both entering as UNIX timestamps, and also in the format YYYY-MM-DD HH:MM:SS.

**Comment by abronte** [comment]
What error are you getting?

**Comment by jkeung** [comment]
I'm not getting any errors in Ruby, but I am unable to see what error is happening in BigQuery because I do not have a jobID to associate the task to insert the rows. Does the insertion of data work by making an api request to add the data? Not sure how I can troubleshoot this without identifying the job in BigQuery.

**Comment by jkeung** [comment]
Nvm non-issue, I got it to work by entering as a UNIX timestamp again! Thanks!
